server:
  port: 8086

spring:
  datasource:
    username: postgres
    password: root
    url: 'jdbc:postgresql://localhost:5432/demoUser'
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#Jwt
jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}