server:
  port: 8088

spring:
  application:
    name: config-server-git
  cloud:
    config:
      server:
        git:
          uri:
          default-label: main
          skip-ssl-validation: true